# Generated by Django 3.1.7 on 2021-02-19 22:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='revision',
            name='slug',
        ),
        migrations.AlterField(
            model_name='revision',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponge.app'),
        ),
    ]
