# Generated by Django 3.1.7 on 2021-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponge', '0003_auto_20210220_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='revision',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
