# Generated by Django 3.1.7 on 2021-02-20 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sponge', '0004_auto_20210220_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
